Repository BHoM/Dynamo_UI, pull requests merged in 2020-06, with the labels that each got.

#238 Remove dependency to UI_PostBuild
  Dynamo13/Dynamo_UI/Dynamo13_UI.csproj
  Dynamo20/Dynamo_UI/Dynamo20_UI.csproj
Labels: type:compliance

#245 Default lacing changed from Shortest to Auto
  Dynamo20/Dynamo_UI/Templates/CallerComponent.cs
  Dynamo20/Dynamo_UI/Templates/CallerValueList.cs
Labels: type:bug

#246 Geometry convert fixes
  Dynamo20/Dynamo_Engine/Convert/FromDesignScript.cs
  Dynamo20/Dynamo_Engine/Objects/DataAccessor_Dynamo.cs
Labels: type:bug

#250 Conversion of closed BHoM Polyline to Polygon implemented
  Dynamo20/Dynamo_Engine/Convert/ToDesignScript.cs
Labels: type:feature
