Repository BHoM/Dynamo_UI, pull requests merged in 2020-01, with the labels that each got.

#190 Update assembly file version to 3.1.0.0
  Dynamo_Engine/Properties/AssemblyInfo.cs
  Dynamo_UI/Properties/AssemblyInfo.cs
Labels: type:compliance

#191 Expose BHoM warnings to the UI
  Dynamo_Engine/Compute/RunCaller.cs
  Dynamo_UI/Templates/CallerComponent.cs
  Dynamo_UI/Templates/CallerValueList.cs
Labels: type:bug

#188 Aligning with changes in BHoMAdapter Refactoring Level 04
  Dynamo_UI/Components/Adapter/Delete.cs
  Dynamo_UI/Global/GlobalSearch.cs
Labels: type:external-api-changes

#201 Add CI files and checks
  .ci/CloneTest.ps1
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
  .ci/testSettings.runsettings
  core.txt
  dependants.txt
  dependencies.txt
Labels: type:compliance
